### ISSUE TITLE
ADD PROPERTY_WRITE_NR

### ISSUE THREAD

**Issue by joseitor** [gb88/BLEOTA#13]
When using an app to send the file, in Android is possible use writeWithoutresponse() againt a PROPERTY_WRITE characteristic, but not in iOS. In ios is necessary to do so, define the characteristics as PROPERTY_WRITE_NR as well.

I have already add  BLECharacteristic::PROPERTY_WRITE_NR in your code, and it's working then in iOS too.

**Comment by gb88** [comment]
Thanks for pointing out, i've also check that in case the packet is bigger of the MTU the writeWithoutResponse is not working, i need to update the webapp to send packet that fit the MTU available. Plese make a pull request. I'm working also on a version with Nimble that seems to improve a bit the speed.

**Comment by gb88** [comment]
updated the code
