### ISSUE TITLE
Add callbacks for OTA_START and OTA_STOP

### ISSUE THREAD

**Issue by drik** [gb88/BLEOTA#4]
This library is great. I really appreciated two aspects:
- it make it easier to integrate it into an existing project (reuse of _pServer and not creating the _pServer like other libraries do)
- it is very interesting to signe the FirmWare

On the other hand, I felt a need to have callbacks before starting the update and at the end of the update.

These callbacks will allow you to perform actions (for example, display on a screen that the device is in update mode) and just after the end of the update, you can inform that the device will restart...

**Comment by gb88** [comment]
Thanks, good point the callback, when i've some spare time i will add it, any contribution is welcome. About the end callback to have time to inform before the restart will be better to move the reset in the callback or outside otherwise the reset will be faster than screen or led refresh

**Comment by drik** [comment]
Hello, @gb88, thanks for your feedback. I submitted a PR with a first design for the callbacks. Feel free to add your comments.
Your comment about the the callback function before calling the ESP.restart() is relevant, but I did not have enough time to analyse how to manage that. You can manage it when you get some spare time.

**Comment by gb88** [comment]
should be closed with the last release [https://github.com/gb88/BLEOTA/releases/tag/v1.0.1](url)
