### ISSUE TITLE
Low tranfer rate

### ISSUE THREAD

**Issue by joseitor** [gb88/BLEOTA#6]
Using your web app, I'm able to transfer at rates below 2kb/s what make it pretty slow for use in a commercial use. I'm doing an Ionic App to try if the rate increase but...
It's that the maximun for you too? If so, we should look for methods to increase it

**Comment by gb88** [comment]
Hi, the transfer speed depends a lot on the ble connection parameters, the webapp running on different phone o PC will give different result, in some test i reach 7/8 kB/s but some improvmentes are possible. I'm also working on Ionic app

**Comment by gb88** [comment]
With the last webapp i was able to reach 6kB/s with PC and 12kB/s with BLE5.0 smartphone

**Comment by joseitor** [comment]
Yeah, thanks! I’ve improved to 2 kb/s. With the phone, I’m still struggling to implement it in my Ionic app. I hope you can do it, upload it, and use part of your code for it.

**Comment by joseitor** [comment]
I have to say that lately I used the Web App from the phone and got speeds up to 20kb/s, what it was more than acceptable for the purpose.  So I guess that the problem at first was my laptop, althought any improvement in the protocol will be welcome. Now just straglelling to pass it to a Ionic App.
