### ISSUE TITLE
NACK on START command

### ISSUE THREAD

**Issue by Lesateq** [gb88/BLEOTA#8]
Hello, thanks for your contribution. I have compiled BLEOTA for ESP32 (NodeMCU Dev board). It seems to work well, but when I connect from the webapp and try to upload a .bin I got an error: NACK on START command.
The webapp connects well, the output I received:

ESP32OTA
Device Information
Manufacturer: Espressif
Model: 1
HW Version: 2
FW Version: 1.0.0

I ran the webapp on Chrome and Edge browsers.
Do you have any suggestions?

**Comment by gb88** [comment]
How big is the .bin file use for the OTA and which ESP32 module is mounted on the dev kit?

**Comment by Lesateq** [comment]
Hello, thanks for your swift reply!. I use a NodeMcu ESP32 Wroom Wifi/ Bluetooth development board with Xtensa 32-bit LX6 Dua-core processor. I can connect Bluetooth to my Windows 11 laptop. However, I cannot connect to my MacAir with bluetooth 5.0. That is peculiar since BLE5.0 should be downwards compatible right? I use your unmodified bleota sketch that compiles into 1.2MB. I am not the most experienced programmer, so perhaps I missed something...

**Comment by gb88** [comment]
Good that you solve with W11 laptop, for the Macbook Air could be some problem with the Web Bluetooth since the web application is based on that, i never tested with Apple device so i don't know what could be, i will check in the documentation of Web Bluetooth if there is something to care on Apple system

**Comment by Lesateq** [comment]
Buona giornata. Meanwhile I found out that other Apple stuff does not work either. I have to find out why, but the ESP32 is not advertised in the Apple bluetooth menu.  So it is not related to your webapp.  By the way, I have installed the Android app and I got an upload speed between 12kb/s and 17 kb/s. That is excellent. Many thanks for your support, the library is a great piece of work! 
If you are interested, check out https://esp32.com/viewtopic.php?p=136040#p136040. Now I have replaced the ArduinoOTA with BLEOTA and everything works perfect. Obviously the usage of ESPNOW communication does not mess up BLEOTA and I am able to flash Sonoff and Athom devices on remote using BLEOTA. For some (chinese) reasons in these devices the 220V mains are connected to the GND of the low voltage circuitry. You have to be very carefull and unplug the mains before connecting FTDI...

**Comment by gb88** [comment]
Great, i'm working on compression of the OTA file to speed up the process, is still experimental but looks promising

**Comment by Lesateq** [comment]
Great, that will speed up the process indeed. Meanwhile I have changed the sketches for Sonof PowElite(powermeter) , Sonoff S60 (smart plug), Athom PG01V3 (smart plug) and WT32SC01Plus (touchscreen) and the upload with BLEOTA is completely flawless :)

**Comment by gb88** [comment]
Yes, check also this : [https://github.com/gb88/BLEOTA/issues/6](https://github.com/gb88/BLEOTA/issues/6)
