### ISSUE TITLE
Web App Timeout?

### ISSUE THREAD

**Issue by krdarrah** [gb88/BLEOTA#9]
Hello - great project and works perfectly sending from my Android tablet, but having issues from:
Intel MacOS Version 14.5
Chrome  v127.0.6533.119
ESP32-C3 Mini 4M  v2.014 Core
Using the bleat example app

Here is the terminal output: 
ota.tsx:251 Scan Clicked
ota.tsx:273 Connected to device
ota.tsx:314 timeout 0x2a25
ota.tsx:515 app
ota.tsx:508 ArrayBuffer(1029184)
ota.tsx:437 Start App OTA
ota.tsx:448 Uint8Array(20)0: 21: 02: 03: 04: 05: 06: 07: 08: 09: 010: 011: 012: 013: 014: 015: 016: 017: 018: 6719: 240offset: (...)parent: (...)buffer: ArrayBuffer(20)byteLength: 20byteOffset: 0length: 20Symbol(Symbol.toStringTag): "Uint8Array"[[Prototype]]: Uint8Array
ota.tsx:229 DataView(20)
ota.tsx:465 cmd acked
ota.tsx:426 timeout2
ota.tsx:170 FW NACK
ota.tsx:469 Stop OTA
ota.tsx:475 Uint8Array(20)0: 21: 02: 03: 04: 05: 06: 07: 08: 09: 010: 011: 012: 013: 014: 015: 016: 017: 018: 6719: 240offset: (...)parent: (...)buffer: ArrayBuffer(20)byteLength: 20byteOffset: 0length: 20Symbol(Symbol.toStringTag): "Uint8Array"[[Prototype]]: Uint8Array
ota.tsx:395 timeout1
ota.tsx:489 NACK
ota.tsx:65 device Tszf3wqoyeikc2z6UyvwHA== disconnected
ota.tsx:251 Scan Clicked
ota.tsx:273 Connected to device
ota.tsx:314 timeout 0x2a25
ota.tsx:515 app
ota.tsx:508 ArrayBuffer(1029184)
ota.tsx:437 Start App OTA
ota.tsx:448 Uint8Array(20) [1, 0, 64, 180, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 74, 251, buffer: ArrayBuffer(20), byteLength: 20, byteOffset: 0, length: 20, Symbol(Symbol.toStringTag): 'Uint8Array']
ota.tsx:229 DataView(20)
ota.tsx:465 cmd acked
ota.tsx:426 timeout2
ota.tsx:170 FW NACK
ota.tsx:469 Stop OTA
ota.tsx:475 Uint8Array(20) [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 67, 240, buffer: ArrayBuffer(20), byteLength: 20, byteOffset: 0, length: 20, Symbol(Symbol.toStringTag): 'Uint8Array']
ota.tsx:395 timeout1
ota.tsx:489 NACK

Let me know if there's anything I do to get this working, thanks!

**Comment by gb88** [comment]
Could be a problem of wrong MTU, since I don't have apple device I've not test the web app on that but I know that web Bluetooth can change behaviour on different device, I will check it

**Comment by gb88** [comment]
I confirm that is a problem of the MTU, i will update the webapp to handle this case

**Comment by gb88** [comment]
there is a problem on the implementation of the MTU dependencies on the web app, ionic not yet support the function in browser, [https://github.com/capacitor-community/bluetooth-le?tab=readme-ov-file#platform-support](https://github.com/capacitor-community/bluetooth-le?tab=readme-ov-file#platform-support)

**Comment by gb88** [comment]
good, i consider the issue closed, keeping in mind that only a mobile app can handle differnet MTU size
